services:
  db:
    image: postgres:latest
    container_name: pgdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  backend:
    image: edwardjamesf/fews-fastapi:latest
    container_name: backend
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_IP_PORT: ${POSTGRES_IP_PORT}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
  frontend:
    image: edwardjamesf/fews-vite-dist:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
        restart: true