FROM python:3.12.3

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY database.py /code/database.py

COPY models.py /code/models.py

COPY main.py /code/main.py

CMD ["fastapi", "run", "main.py", "--port", "8000"]
